import platform
import os

ccflags = "-std=c++11 -Wall -I../../include -O2"

if platform.system() == "Windows":
    env = Environment(tools = ["mingw"], CCFLAGS = ccflags, ENV = os.environ)
else:
    env = Environment(CCFLAGS = ccflags, ENV = os.environ)

env.Program(target = "sample", source = Split("sample.cc"))
